### ISSUE TITLE
Fonts in blogs are too large, width of the text too narrow

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange-hugo#114]
The page style in blogs, say in [a recent blog](http://localhost:1313/blog/2020/2020-01-08-neighbors-images/), should match other page styles, say those used in the presentation of features, like on the page for [interactive data visualization](http://localhost:1313/home/interactive_data_visualization/). 

- match the font size (the font in blogs is too big)
- match the width of the page (blog pages are too narrow)

**Comment by ajdapretnar** [comment]
I think the current style is a major improvement over what we had before. The font size and width match guidelines for blogs. The bigger the text and the narrower the width, the easier they are to read.

I think the final parameters should be decided with @markotoplak and @irgolic.

**Comment by irgolic** [comment]
Opening a blog in Firefox's reader view shows it like this:

![Screenshot 2020-01-09 at 13 17 11](https://user-images.githubusercontent.com/24586651/72067130-fd77cb80-32d9-11ea-8bee-dcb6d4ca7a5c.png)

The width is even smaller than it is on our site, likely due to readability like @ajdapretnar said (it's easier to find the start of the next line, jumping from right to left).

In a bit I'm going to put up a PR for changing the font size, and top-bottom padding for the title and images.

**Comment by markotoplak** [comment]
I'd guess that the real cause for this issue is not in the specifics, but is a general "it does not look good". I do agree with this: it does not.

I'd say the text-width is fine, it just does not fit well with the rest of the layout.

And the font we are using is not exactly the most readable font ever. I think we should consider changing it. On the whole page.

**Comment by ajdapretnar** [comment]
I disagree. I think blog looks much better than the rest of the page. It is readable.

We experimented with @irgolic and changed the rest of the website to be more like the blog and it looked really good.

As for the changes in the blog, they were modeled by industry standards and general recommendations for blog posts. We are using Lato, which is considered a very good font for the website. FRI also uses it, which make our pages a little bit more in line. See: https://blogcharge.com/best-google-fonts/

**Comment by irgolic** [comment]
The fonts are different for me on Firefox and Chrome. I'm not sure what causes this, might be my specific setup.
